language: julia

julia:
  - 0.5
  - 0.6

env:
  global:
    - APM_TEST_PACKAGES="ink language-julia"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ""
    - ATOMJL=master

os:
  - linux

matrix:
  include:
    # Sanity check for OS X
    - os: osx
      julia: 0.5
      env: ATOMJL=master
    # Sanity check for Atom Beta
    - os: linux
      julia: 0.5
      env: ATOM_CHANNEL=beta

script:
  - julia ci/packages.jl
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - bash build-package.sh

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

notifications:
    email: false